USE ProyectoFinalSQL;
GO

/*ELIMINAR TABLAS*/

DROP TABLE IF EXISTS silver.PEDIDOS;
DROP TABLE IF EXISTS silver.RECETA;
DROP TABLE IF EXISTS silver.INVENTARIO;
DROP TABLE IF EXISTS silver.ROTACION_TURNOS;
DROP TABLE IF EXISTS silver.EMPLEADOS;
DROP TABLE IF EXISTS silver.TURNOS;
DROP TABLE IF EXISTS silver.INGREDIENTES;
DROP TABLE IF EXISTS silver.PRODUCTOS;
GO



/*CREACION TABLAS SILVER*/

CREATE TABLE silver.DIRECCIONES
(
ID_DIRECCION			INT PRIMARY KEY,
DIR_DELIVERY_PRIN		VARCHAR(200),
DIR_DELIVERY_SEC		VARCHAR(200),
CIUDAD_DELIVERY			VARCHAR(200),
FECHA_CARGA				DATETIME DEFAULT GETDATE() 
);

GO

CREATE TABLE silver.CLIENTES (
    ID_CLIENTE      INT PRIMARY KEY,
    NOMBRE_CLIENTE  VARCHAR(200),
    APELLIDO_CLIENTE VARCHAR(200)
);

GO

CREATE TABLE silver.INGREDIENTES
(
ID_INGRED       VARCHAR(20) PRIMARY KEY,
NOMBRE_INGRED   VARCHAR(200),
PESO_INGRED     VARCHAR(200),
MEDIDA_INGRED   VARCHAR(200),
PRECIO_INGRED   FLOAT,
FECHA_CARGA     DATETIME DEFAULT GETDATE()
);

GO

CREATE TABLE silver.INVENTARIO
(
ID_INVENTARIO  INT PRIMARY KEY,
ID_INGRED      VARCHAR(20),  
CANTIDAD       INT,
FECHA_CARGA    DATETIME DEFAULT GETDATE()
);

GO

CREATE TABLE silver.PRODUCTOS
(
ID_PRODUCTO     VARCHAR(20) PRIMARY KEY,
SKU             VARCHAR(200),
NOMBRE_PRODUCTO VARCHAR(200),
CAT_PRODUCTO    VARCHAR(200),
FORMA_PRODUCTO  VARCHAR(200),
PRECIO_PRODUCTO FLOAT,
FECHA_CARGA     DATETIME DEFAULT GETDATE()
);

GO

CREATE TABLE silver.PEDIDOS
(
ID_PEDIDO            VARCHAR(20),
ID_CLIENTE           INT,
FECHA_CREACION        DATE,
FECHA_HORA_CREACION   DATETIME,
ID_PRODUCTO           VARCHAR(20),
CANTIDAD              INT,
FLG_DELIVERY          BIT,
ID_DIRECCION          INT,
FECHA_CARGA           DATETIME DEFAULT GETDATE(),
PRIMARY KEY (ID_PEDIDO, ID_PRODUCTO)
);

GO

CREATE TABLE silver.RECETA
(
ID_PRODUCTO   VARCHAR(20),   
ID_INGRED     VARCHAR(20),   
CANTIDAD      INT,
FECHA_CARGA   DATETIME DEFAULT GETDATE(),
PRIMARY KEY (ID_PRODUCTO, ID_INGRED)
);

GO

CREATE TABLE silver.ROTACION_TURNOS
(
ID_ROTACION   VARCHAR(20),
FECHA         DATE,
ID_TURNO      VARCHAR(20),
ID_EMPLEADO   VARCHAR(20),
FECHA_CARGA   DATETIME DEFAULT GETDATE(),
PRIMARY KEY (ID_ROTACION, ID_TURNO, ID_EMPLEADO)
);

GO

CREATE TABLE silver.TURNOS
(
ID_TURNO     VARCHAR(20) PRIMARY KEY,
DIA_SEMANA   VARCHAR(200),
HORA_INICIO  TIME,
HORA_FIN     TIME,
FECHA_CARGA  DATETIME DEFAULT GETDATE()
);

GO

CREATE TABLE silver.EMPLEADOS
(
ID_EMPLEADO  VARCHAR(20) PRIMARY KEY,
NOMBRES      VARCHAR(200),
APELLIDOS    VARCHAR(200),
CARGO        VARCHAR(200),
TARIFA_HORA  FLOAT,
FECHA_CARGA  DATETIME DEFAULT GETDATE()
);

GO

  /*FOREIGN KEYS - CAPA SILVER*/

   
ALTER TABLE silver.PEDIDOS
ADD CONSTRAINT FK_PEDIDOS_CLIENTE   FOREIGN KEY (ID_CLIENTE)   REFERENCES silver.CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_PEDIDOS_PRODUCTO  FOREIGN KEY (ID_PRODUCTO)  REFERENCES silver.PRODUCTOS(ID_PRODUCTO),
    CONSTRAINT FK_PEDIDOS_DIRECCION FOREIGN KEY (ID_DIRECCION) REFERENCES silver.DIRECCIONES(ID_DIRECCION);
GO

ALTER TABLE silver.RECETA
ADD CONSTRAINT FK_RECETA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES silver.PRODUCTOS(ID_PRODUCTO),
    CONSTRAINT FK_RECETA_INGRED   FOREIGN KEY (ID_INGRED)   REFERENCES silver.INGREDIENTES(ID_INGRED);
GO

ALTER TABLE silver.INVENTARIO
ADD CONSTRAINT FK_INVENTARIO_INGRED FOREIGN KEY (ID_INGRED) REFERENCES silver.INGREDIENTES(ID_INGRED);
GO

ALTER TABLE silver.ROTACION_TURNOS
ADD CONSTRAINT FK_ROTACION_TURNO    FOREIGN KEY (ID_TURNO)    REFERENCES silver.TURNOS(ID_TURNO),
    CONSTRAINT FK_ROTACION_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES silver.EMPLEADOS(ID_EMPLEADO);
GO
/*1. TABLAS SIN DEPENDENCIAS (padres)*/


INSERT INTO silver.DIRECCIONES (ID_DIRECCION, DIR_DELIVERY_PRIN, DIR_DELIVERY_SEC, CIUDAD_DELIVERY)
SELECT
    ID_DIRECCION,
    LTRIM(RTRIM(DIR_DELIVERY_PRIN)),
    NULLIF(LTRIM(RTRIM(DIR_DELIVERY_SEC)), ''),
    LTRIM(RTRIM(CIUDAD_DELIVERY))
FROM bronze.DIRECCIONES_RAW;
GO

INSERT INTO silver.CLIENTES (ID_CLIENTE, NOMBRE_CLIENTE, APELLIDO_CLIENTE)
SELECT DISTINCT
    TRY_CAST(ID_CLIENTE AS INT),
    NULLIF(LTRIM(RTRIM(NOMBRE_CLIENTE)), ''),
    NULLIF(LTRIM(RTRIM(APELLIDO_CLIENTE)), '')
FROM bronze.CLIENTES_RAW
WHERE TRY_CAST(ID_CLIENTE AS INT) IS NOT NULL;
GO

INSERT INTO silver.INGREDIENTES (ID_INGRED, NOMBRE_INGRED, PESO_INGRED, MEDIDA_INGRED, PRECIO_INGRED)
SELECT DISTINCT
    LTRIM(RTRIM(ID_INGRED)),
    LTRIM(RTRIM(NOMBRE_INGRED)),
    LTRIM(RTRIM(PESO_INGRED)),
    LTRIM(RTRIM(MEDIDA_INGRED)),
    TRY_CAST(LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(PRECIO_INGRED, CHAR(13), ''), CHAR(10), ''), CHAR(9), ''))) AS FLOAT)
FROM bronze.INGREDIENTES_RAW
WHERE ID_INGRED IS NOT NULL AND LTRIM(RTRIM(ID_INGRED)) <> '';
GO

INSERT INTO silver.PRODUCTOS (ID_PRODUCTO, SKU, NOMBRE_PRODUCTO, CAT_PRODUCTO, FORMA_PRODUCTO, PRECIO_PRODUCTO)
SELECT DISTINCT
    LTRIM(RTRIM(ID_PRODUCTO)),
    LTRIM(RTRIM(SKU)),
    LTRIM(RTRIM(NOMBRE_PRODUCTO)),
    LTRIM(RTRIM(CAT_PRODUCTO)),
    LTRIM(RTRIM(FORMA_PRODUCTO)),
    TRY_CAST(LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(PRECIO_PRODUCTO, CHAR(13), ''), CHAR(10), ''), CHAR(9), ''))) AS FLOAT)
FROM bronze.PRODUCTOS_RAW
WHERE ID_PRODUCTO IS NOT NULL AND LTRIM(RTRIM(ID_PRODUCTO)) <> '';
GO

INSERT INTO silver.TURNOS (ID_TURNO, DIA_SEMANA, HORA_INICIO, HORA_FIN)
SELECT DISTINCT
    LTRIM(RTRIM(ID_TURNO)),
    LTRIM(RTRIM(DIA_SEMANA)),
    TRY_CAST(LTRIM(RTRIM(HORA_INICIO)) AS TIME),
    TRY_CAST(LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(HORA_FIN, CHAR(13), ''), CHAR(10), ''), CHAR(9), ''))) AS TIME)
FROM bronze.TURNOS_RAW
WHERE ID_TURNO IS NOT NULL AND LTRIM(RTRIM(ID_TURNO)) <> '';
GO

INSERT INTO silver.EMPLEADOS (ID_EMPLEADO, NOMBRES, APELLIDOS, CARGO, TARIFA_HORA)
SELECT DISTINCT
    LTRIM(RTRIM(ID_EMPLEADO)),
    LTRIM(RTRIM(NOMBRES)),
    LTRIM(RTRIM(APELLIDOS)),
    LTRIM(RTRIM(CARGO)),
    TRY_CAST(LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(TARIFA_HORA, CHAR(13), ''), CHAR(10), ''), CHAR(9), ''))) AS FLOAT)
FROM bronze.EMPLEADOS_RAW
WHERE ID_EMPLEADO IS NOT NULL AND LTRIM(RTRIM(ID_EMPLEADO)) <> '';
GO

INSERT INTO silver.PEDIDOS (ID_PEDIDO, ID_CLIENTE, FECHA_CREACION, FECHA_HORA_CREACION, ID_PRODUCTO, CANTIDAD, FLG_DELIVERY, ID_DIRECCION)
SELECT
    LTRIM(RTRIM(p.ID_PEDIDO)),
    MAX(TRY_CAST(p.ID_CLIENTE AS INT)),
    MAX(TRY_CAST(p.FECHA_CREACION AS DATE)),
    MAX(TRY_CAST(p.FECHA_HORA_CREACION AS DATETIME)),
    LTRIM(RTRIM(p.ID_PRODUCTO)),
    SUM(TRY_CAST(p.CANTIDAD AS INT)),
    MAX(TRY_CAST(p.FLG_DELIVERY AS INT)),
    MAX(TRY_CAST(LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(p.ID_DIRECCION, CHAR(13), ''), CHAR(10), ''), CHAR(9), ''))) AS INT))
FROM bronze.PEDIDOS_RAW p
WHERE p.ID_PEDIDO IS NOT NULL AND LTRIM(RTRIM(p.ID_PEDIDO)) <> ''
  AND EXISTS (SELECT 1 FROM silver.CLIENTES c WHERE c.ID_CLIENTE = TRY_CAST(p.ID_CLIENTE AS INT))
  AND EXISTS (SELECT 1 FROM silver.PRODUCTOS pr WHERE pr.ID_PRODUCTO = LTRIM(RTRIM(p.ID_PRODUCTO)))
  AND EXISTS (
      SELECT 1 FROM silver.DIRECCIONES d
      WHERE d.ID_DIRECCION = TRY_CAST(LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(p.ID_DIRECCION, CHAR(13), ''), CHAR(10), ''), CHAR(9), ''))) AS INT)
  )
GROUP BY LTRIM(RTRIM(p.ID_PEDIDO)), LTRIM(RTRIM(p.ID_PRODUCTO));
GO

INSERT INTO silver.RECETA (ID_PRODUCTO, ID_INGRED, CANTIDAD)
SELECT DISTINCT
    pr.ID_PRODUCTO,
    LTRIM(RTRIM(r.ID_INGRED)),
    TRY_CAST(LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(r.CANTIDAD, CHAR(13), ''), CHAR(10), ''), CHAR(9), ''))) AS INT)
FROM bronze.RECETA_RAW r
INNER JOIN silver.PRODUCTOS pr ON pr.SKU = LTRIM(RTRIM(r.ID_PRODUCTO))
WHERE r.ID_INGRED IS NOT NULL
  AND EXISTS (SELECT 1 FROM silver.INGREDIENTES i WHERE i.ID_INGRED = LTRIM(RTRIM(r.ID_INGRED)));
GO

INSERT INTO silver.INVENTARIO (ID_INVENTARIO, ID_INGRED, CANTIDAD)
SELECT DISTINCT
    TRY_CAST(inv.ID_INVENTARIO AS INT),
    LTRIM(RTRIM(inv.ID_INGRED)),
    TRY_CAST(LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(inv.CANTIDAD, CHAR(13), ''), CHAR(10), ''), CHAR(9), ''))) AS INT)
FROM bronze.INVENTARIO_RAW inv
WHERE TRY_CAST(inv.ID_INVENTARIO AS INT) IS NOT NULL
  AND EXISTS (SELECT 1 FROM silver.INGREDIENTES i WHERE i.ID_INGRED = LTRIM(RTRIM(inv.ID_INGRED)));
GO

INSERT INTO silver.ROTACION_TURNOS (ID_ROTACION, FECHA, ID_TURNO, ID_EMPLEADO)
SELECT DISTINCT
    LTRIM(RTRIM(rt.ID_ROTACION)),
    TRY_CAST(rt.FECHA AS DATE),
    LTRIM(RTRIM(rt.ID_TURNO)),
    LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(rt.ID_EMPLEADO, CHAR(13), ''), CHAR(10), ''), CHAR(9), '')))
FROM bronze.ROTACION_TURNOS_RAW rt
WHERE rt.ID_ROTACION IS NOT NULL AND LTRIM(RTRIM(rt.ID_ROTACION)) <> ''
  AND EXISTS (SELECT 1 FROM silver.TURNOS t WHERE t.ID_TURNO = LTRIM(RTRIM(rt.ID_TURNO)))
  AND EXISTS (
      SELECT 1 FROM silver.EMPLEADOS e
      WHERE e.ID_EMPLEADO = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(rt.ID_EMPLEADO, CHAR(13), ''), CHAR(10), ''), CHAR(9), '')))
  );
GO

/*Validación*/
SELECT * FROM silver.DIRECCIONES;
SELECT * FROM silver.CLIENTES;
SELECT * FROM silver.INGREDIENTES;
SELECT * FROM silver.INVENTARIO;
SELECT * FROM silver.PRODUCTOS;
SELECT * FROM silver.PEDIDOS;
SELECT * FROM silver.RECETA;
SELECT * FROM silver.ROTACION_TURNOS;
SELECT * FROM silver.TURNOS;
SELECT * FROM silver.EMPLEADOS;


