/*CREAR DATABASE*/
CREATE DATABASE ProyectoFinalSQL;
GO

/*CREAR CAPAS EN EL DATABASE*/
USE ProyectoFinalSQL;
GO

CREATE SCHEMA bronze;
GO
CREATE SCHEMA silver;
GO
CREATE SCHEMA gold;
GO

/*CREACION DE TABLAS EN CAPA BRONZE*/

CREATE TABLE bronze.DIRECCIONES_RAW

(
ID_DIRECCION			INT IDENTITY (1,1),
DIR_DELIVERY_PRIN		VARCHAR(200),
DIR_DELIVERY_SEC		VARCHAR(200),
CIUDAD_DELIVERY			VARCHAR(200),
FECHA_CARGA				DATETIME DEFAULT GETDATE() 
)

GO

CREATE TABLE bronze.CLIENTES_RAW

(
ID_CLIENTE				VARCHAR(200),
NOMBRE_CLIENTE			VARCHAR(200),
APELLIDO_CLIENTE		VARCHAR(200),
FECHA_CARGA				DATETIME DEFAULT GETDATE() 
)

GO

CREATE TABLE bronze.INGREDIENTES_RAW

(
ID_INGRED				VARCHAR(200),
NOMBRE_INGRED			VARCHAR(200),
PESO_INGRED				VARCHAR(200),
MEDIDA_INGRED			VARCHAR(200),
PRECIO_INGRED			VARCHAR(200),
FECHA_CARGA				DATETIME DEFAULT GETDATE() 
)

GO

CREATE TABLE bronze.INVENTARIO_RAW

(
ID_INVENTARIO			VARCHAR(200),
ID_INGRED				VARCHAR(200),
CANTIDAD				VARCHAR(200),
FECHA_CARGA				DATETIME DEFAULT GETDATE() 
)

GO

CREATE TABLE bronze.PRODUCTOS_RAW
(
ID_PRODUCTO				VARCHAR(200),
SKU						VARCHAR(200),
NOMBRE_PRODUCTO			VARCHAR(200),
CAT_PRODUCTO			VARCHAR(200),
FORMA_PRODUCTO			VARCHAR(200),
PRECIO_PRODUCTO			VARCHAR(200),
FECHA_CARGA				DATETIME DEFAULT GETDATE() 
)

GO

CREATE TABLE bronze.PEDIDOS_RAW 
(
ID_FILA					VARCHAR(200),
ID_PEDIDO				VARCHAR(200),
ID_CLIENTE				VARCHAR(200),
FECHA_CREACION			VARCHAR(200),
FECHA_HORA_CREACION		VARCHAR(200),
ID_PRODUCTO				VARCHAR(200),
CANTIDAD				VARCHAR(200),
FLG_DELIVERY			VARCHAR(200),
ID_DIRECCION			VARCHAR(200),
FECHA_CARGA				DATETIME DEFAULT GETDATE() 
)

GO

CREATE TABLE bronze.RECETA_RAW
(
ID_FILA				VARCHAR(200),
ID_PRODUCTO			VARCHAR(200),
ID_INGRED			VARCHAR(200),
CANTIDAD			VARCHAR(200),
FECHA_CARGA				DATETIME DEFAULT GETDATE() 
)

GO

CREATE TABLE bronze.ROTACION_TURNOS_RAW
(
ID_FILA				VARCHAR(200),
ID_ROTACION			VARCHAR(200),
FECHA				VARCHAR(200),
ID_TURNO			VARCHAR(200),
ID_EMPLEADO			VARCHAR(200),
FECHA_CARGA				DATETIME DEFAULT GETDATE() 
)

GO

CREATE TABLE bronze.TURNOS_RAW
(
ID_TURNO			VARCHAR(200),
DIA_SEMANA			VARCHAR(200),
HORA_INICIO			VARCHAR(200),
HORA_FIN			VARCHAR(200),
FECHA_CARGA				DATETIME DEFAULT GETDATE() 
)

GO

CREATE TABLE bronze.EMPLEADOS_RAW
(
ID_EMPLEADO			VARCHAR(200),
NOMBRES				VARCHAR(200),
APELLIDOS			VARCHAR(200),
CARGO				VARCHAR(200),
TARIFA_HORA			VARCHAR(200),
FECHA_CARGA				DATETIME DEFAULT GETDATE() 
)

GO


/*CREAR VISTAS PARA TRAER LA DATA*/

CREATE VIEW bronze.vw_load_direcciones AS
SELECT DIR_DELIVERY_PRIN, DIR_DELIVERY_SEC, CIUDAD_DELIVERY
FROM bronze.DIRECCIONES_RAW;
GO

CREATE VIEW bronze.vw_load_clientes AS
SELECT ID_CLIENTE, NOMBRE_CLIENTE, APELLIDO_CLIENTE
FROM bronze.CLIENTES_RAW;
GO

CREATE VIEW bronze.vw_load_ingredientes AS
SELECT ID_INGRED, NOMBRE_INGRED, PESO_INGRED, MEDIDA_INGRED, PRECIO_INGRED
FROM bronze.INGREDIENTES_RAW;
GO

CREATE VIEW bronze.vw_load_inventario AS
SELECT ID_INVENTARIO, ID_INGRED, CANTIDAD
FROM bronze.INVENTARIO_RAW;
GO

CREATE VIEW bronze.vw_load_productos AS
SELECT ID_PRODUCTO, SKU, NOMBRE_PRODUCTO, CAT_PRODUCTO, FORMA_PRODUCTO, PRECIO_PRODUCTO
FROM bronze.PRODUCTOS_RAW;
GO

CREATE VIEW bronze.vw_load_pedidos AS
SELECT ID_FILA, ID_PEDIDO, ID_CLIENTE, FECHA_CREACION, FECHA_HORA_CREACION, ID_PRODUCTO, CANTIDAD, FLG_DELIVERY, ID_DIRECCION
FROM bronze.PEDIDOS_RAW;
GO

CREATE VIEW bronze.vw_load_receta AS
SELECT ID_FILA, ID_PRODUCTO, ID_INGRED, CANTIDAD
FROM bronze.RECETA_RAW;
GO

CREATE VIEW bronze.vw_load_rotacion AS
SELECT ID_FILA, ID_ROTACION, FECHA, ID_TURNO, ID_EMPLEADO
FROM bronze.ROTACION_TURNOS_RAW;
GO

CREATE VIEW bronze.vw_load_turnos AS
SELECT ID_TURNO, DIA_SEMANA, HORA_INICIO, HORA_FIN
FROM bronze.TURNOS_RAW;
GO

CREATE VIEW bronze.vw_load_empleados AS
SELECT ID_EMPLEADO, NOMBRES, APELLIDOS, CARGO, TARIFA_HORA
FROM bronze.EMPLEADOS_RAW;
GO

/*INSERTAR LA DATA*/

BULK INSERT bronze.vw_load_direcciones
FROM 'C:\Users\ARATH\Desktop\CURSO SQL FOR DATA ENGINEER\PROYECTO\Addresses.csv'
WITH (FORMAT='CSV', FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT bronze.vw_load_clientes
FROM 'C:\Users\ARATH\Desktop\CURSO SQL FOR DATA ENGINEER\PROYECTO\Customers.csv'
WITH (FORMAT='CSV', FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT bronze.vw_load_ingredientes
FROM 'C:\Users\ARATH\Desktop\CURSO SQL FOR DATA ENGINEER\PROYECTO\Ingredients.csv'
WITH (FORMAT='CSV', FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT bronze.vw_load_inventario
FROM 'C:\Users\ARATH\Desktop\CURSO SQL FOR DATA ENGINEER\PROYECTO\Inventory.csv'
WITH (FORMAT='CSV', FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT bronze.vw_load_productos
FROM 'C:\Users\ARATH\Desktop\CURSO SQL FOR DATA ENGINEER\PROYECTO\Items.csv'
WITH (FORMAT='CSV', FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT bronze.vw_load_pedidos
FROM 'C:\Users\ARATH\Desktop\CURSO SQL FOR DATA ENGINEER\PROYECTO\Orders.csv'
WITH (FORMAT='CSV', FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT bronze.vw_load_receta
FROM 'C:\Users\ARATH\Desktop\CURSO SQL FOR DATA ENGINEER\PROYECTO\Recipe.csv'
WITH (FORMAT='CSV', FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT bronze.vw_load_rotacion
FROM 'C:\Users\ARATH\Desktop\CURSO SQL FOR DATA ENGINEER\PROYECTO\Rotation.csv'
WITH (FORMAT='CSV', FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT bronze.vw_load_turnos
FROM 'C:\Users\ARATH\Desktop\CURSO SQL FOR DATA ENGINEER\PROYECTO\Shifts.csv'
WITH (FORMAT='CSV', FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT bronze.vw_load_empleados
FROM 'C:\Users\ARATH\Desktop\CURSO SQL FOR DATA ENGINEER\PROYECTO\Staff.csv'
WITH (FORMAT='CSV', FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

